### ISSUE TITLE
RangeError: Maximum call stack size exceeded at XMLHttpRequest.open [as _open] (JavaScriptServlet:91)

### ISSUE THREAD

**Issue by ashok003** [aramrami/OWASP-CSRFGuard#92] opened 2018-01-04 20:34 UTC
I am getting below error in Chrome browser console when I include JavaScriptServlet in my page. 
My Ajax call stop working from that page.

Uncaught

RangeError: Maximum call stack size exceeded at XMLHttpRequest.open [as _open] (JavaScriptServlet:91)
 at XMLHttpRequest.open [as _open] (JavaScriptServlet:94) at
 XMLHttpRequest.open [as _open] (JavaScriptServlet:94) at XMLHttpRequest.open
 [as _open] (JavaScriptServlet:94) at XMLHttpRequest.open [as
 _open] (JavaScriptServlet:94) at XMLHttpRequest.open [as _open]
 (JavaScriptServlet:94) at XMLHttpRequest.open [as _open] (JavaScriptServlet:94)
 at XMLHttpRequest.open [as _open] (JavaScriptServlet:94) at
 XMLHttpRequest.open [as _open] (JavaScriptServlet:94) at XMLHttpRequest.open
 [as _open] (JavaScriptServlet:94)

**Comment by ShwetaDua** [comment] 2018-07-27 06:46
i am getting same exception..how did you resolve it?

**Comment by vnayak1** [comment] 2019-05-15 20:07
I have come across this issue and couldn't seem to find solution. Please include the solution to this issue in next release. Thank you

**Comment by glitchcube** [comment] 2019-08-21 21:48
Can someone provide an example project on how to recreate this issue? I have not seen this issue myself.

**Comment by mmosoll** [comment] 2019-09-13 13:18
I have the same error, it's difficult to share a sample code to reproduce it. But it's strange, by doing F5 on the same page, we have no more error. Only during the initial loading of the page

**Comment by ashok003** [comment] 2019-09-13 22:44
For token injection, I was using dom manipulation by putting below script in my jsp pages
<script src="./JavaScriptServlet"></script>

The page which was giving above error was having this script included multiple times. It was getting multiple entries from other included jsps within this page. 

Make sure this script gets into ur jsp page only once.

**Comment by mmosoll** [comment] 2019-09-16 09:58
> For token injection, I was using dom manipulation by putting below script in my jsp pages
> 
> <script src="./JavaScriptServlet"></script>
> The page which was giving above error was having this script included multiple times. It was getting multiple entries from other included jsps within this page.
> 
> Make sure this script gets into ur jsp page only once.

Thank you, we have the same problem. Following your comment we solved it.

**Comment by glitchcube** [comment] 2019-09-22 08:01
I have made a pull-request with a possible solution to this error. This will avoid getting this error if the JavaScript file is added multiple times on a page.

**Comment by aramrami** [comment] 2021-02-08 20:08
You can find the newly updated and reworked, soon-to-be-released code-base currently at : 

https://github.com/aramrami/OWASP-CSRFGuard

Doing a mvn clean install -DskipTests then a mvn -DskipTests pre-integration-test -pdeploy-jsp-webapp should build the project and start the test application on port 8080.
The information is also available at the https://github.com/aramrami/OWASP-CSRFGuard#building-the-code

p.s. Please disregard the IFrame and IMG tag errors at the javascript page within the test application, because it is a special scenario/known limitation that will be documented accordingly.

**Comment by forgedhallpass** [comment] 2021-09-15 10:12
The issue seems to be solved, hence closing it.

**Closed by forgedhallpass** 2021-09-15 10:12 UTC
