### ISSUE TITLE
Invalid links in csrfguard.properties

### ISSUE THREAD

**Issue by stefano-1973** [aramrami/OWASP-CSRFGuard#159] opened 2021-11-09 14:36 UTC
In OWASP-CSRFGuard/csrfguard/src/main/resources/csrfguard.properties this link
https://www.owasp.org/index.php/CSRFGuard_3_Token_Injection
is not valid. The page doesn't exists anymore and reditect to https://owasp.org/www-project-csrfguard/

May be at the moment can be substituted with https://wiki.owasp.org/index.php/CSRFGuard_3_Token_Injection waiting a 4.0 updated page?

P.S.: the documentation to the usage of the 4.x library doesn't exists and also the old documentation of 3.1.0 has been removed (the page doesn't exist anymore using the old link http://www.owasp.org/index.php/CSRFGuard-3- Configuration). If someone want the old documentation it can be found here: https://wiki.owasp.org/index.php/CSRFGuard_3_User_Manual

**Comment by forgedhallpass** [comment] 2021-11-09 16:07
Hello @stefano-1973 

Thank you for creating the ticket.  Indeed, currently the only relevant documentation for `4.x` can be found in the`README.md` page and the `csrfguard.properties` file.

p.s. We also welcome contributions if you would consider doing so.

**Comment by forgedhallpass** [comment] 2021-11-10 08:40
Duplicate of https://github.com/OWASP/www-project-csrfguard/issues/36

**Closed by forgedhallpass** 2021-11-10 08:40 UTC
Labels: help wanted, documentation
