### ISSUE TITLE
IE11 error: startsWith not supported

### ISSUE THREAD

**Issue by stefano-1973** [aramrami/OWASP-CSRFGuard#160] opened 2021-11-09 17:49 UTC
The normalizeUrl and calculatePageTokenForUri functions in csrfguard.js use a function not supported by IE11: startsWith
For example in the library there is this:

let normalizedUrl = url.startsWith('/') ? url : '/' + url;

I see that you have already created the function _startsWith(s, prefix)_ but you have not used it in the above instruction (and others)

**Comment by forgedhallpass** [comment] 2021-11-10 08:44
Duplicate of https://github.com/OWASP/www-project-csrfguard/issues/35

**Closed as completed by forgedhallpass** 2021-11-10 08:44 UTC
Labels: duplicate
