### ISSUE TITLE
CsrfGuard on IE9 and IE10 can change XMLHttpRequest like standard browser.

### ISSUE THREAD

**Issue by langelov** [aramrami/OWASP-CSRFGuard#43] opened 2015-11-23 12:38 UTC
When hijacking XMLHttpRequest object there's special case for IE.
This special case is working for versions less than IE9, but don't properly hijack XHRv2 object in IE9 and IE10.
    if (navigator.appName == "Microsoft Internet Explorer")
can be changed to 
    if (document.all && !document.addEventListener); // This catches everything lower than IE9

The problem was found during developing an Angular.js custom tag, which is loading template from external html with ajax call.
Angular.js relies on "onload" event handler, and csrfguard is only providing "onrequeststatechange".

**Comment by 40rn05lyv** [comment] 2015-11-24 07:25
Angular.js uses mainly AJAX communication with server, and, therefore, can be very easily protected using built-in features: https://docs.angularjs.org/api/ng/service/$http . Did you try it?

**Comment by jrauschenbusch** [comment] 2015-11-24 09:54
@40rn05lyv But this still solves not the problem that the hijacking for IE9/10 is broken. For IE9/10 the standard hijacking function should be used.

@langelov +1 for your bug fix

**Comment by 40rn05lyv** [comment] 2015-11-24 09:59
@jrauschenbusch I don't understand how it can work in IE9+ and doesn't work in other IE browsers:
1. `onload` property was introduced in XHRv1, not XHRv2
2. Angular.js doesn't support IE8 and lower

**Comment by 40rn05lyv** [comment] 2015-11-24 10:11
Actually, `onload` property was introduced in XHRv1, not XHRv2. Secondly, XHRv2 is supported only since IE10 (http://caniuse.com/#feat=xhr2). So, it's better to check for ability to use XMLHttpRequest.

From

```
        if(navigator.appName == "Microsoft Internet Explorer") {
            hijackExplorer();
        } else {
            hijackStandard();
        }
```

to 

```
function hasValidXHR() {
    try { new window.XMLHttpRequest(); return true;} catch { return false; } 
}
        if(navigator.appName == "Microsoft Internet Explorer" && !hasValidXHR()) {
            hijackExplorer();
        } else {
            hijackStandard();
        }

```

**Comment by jrauschenbusch** [comment] 2015-11-24 11:14
You are right. The onload event was introduced with XHRv1. The problem is that some libraries like AngularJS or jQuery relies on an onload-Event. But the onload-Event won't be fired in IE10 while hijackExplorer() is used.

I've got that problem while using jQuery.getScript to load an AngularJS script asynchonously. Neither the success nor the error callback handler were called.

**Comment by aramrami** [comment] 2015-12-18 00:26
What is the issue with CSRFGuard?
I will close this issue until you give more explanation.

**Closed by aramrami** 2015-12-18 00:26 UTC
